"""empty message

Revision ID: 1624b2f813d5
Revises: 943edbb281c7
Create Date: 2024-05-06 20:26:42.420114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1624b2f813d5'
down_revision = '943edbb281c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('attendance_lists_id_meal_type_fkey', 'attendance_lists', type_='foreignkey')
    op.drop_constraint('attendance_lists_id_student_fkey', 'attendance_lists', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_lists', 'meal_types', ['id_meal_type'], ['id_meal_type'])
    op.create_foreign_key(None, 'attendance_lists', 'students', ['id_student'], ['id_student'])
    op.add_column('intendants', sa.Column('is_main_admin', sa.Boolean(), nullable=False))
    op.add_column('intendants', sa.Column('id_user', sa.Integer(), nullable=False))
    op.drop_index('ix_intendants_email', table_name='intendants')
    op.create_foreign_key(None, 'intendants', 'users', ['id_user'], ['id_user'])
    op.drop_column('intendants', 'hashed_password')
    op.drop_column('intendants', 'last_name')
    op.drop_column('intendants', 'first_name')
    op.drop_column('intendants', 'email')
    op.create_foreign_key(None, 'meal_rules', 'meal_types', ['id_meal_type'], ['id_meal_type'])
    op.create_foreign_key(None, 'meal_rules', 'students', ['id_student'], ['id_student'])
    op.drop_constraint('students_id_school_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'schools', ['id_school'], ['id_school'])
    op.create_foreign_key(None, 'transactions', 'products', ['id_product'], ['id_product'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_id_school_fkey', 'students', 'units', ['id_school'], ['id_unit'])
    op.drop_constraint(None, 'meal_rules', type_='foreignkey')
    op.drop_constraint(None, 'meal_rules', type_='foreignkey')
    op.add_column('intendants', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('intendants', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('intendants', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('intendants', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'intendants', type_='foreignkey')
    op.create_index('ix_intendants_email', 'intendants', ['email'], unique=False)
    op.drop_column('intendants', 'id_user')
    op.drop_column('intendants', 'is_main_admin')
    op.drop_constraint(None, 'attendance_lists', type_='foreignkey')
    op.drop_constraint(None, 'attendance_lists', type_='foreignkey')
    op.create_foreign_key('attendance_lists_id_student_fkey', 'attendance_lists', 'units', ['id_student'], ['id_unit'])
    op.create_foreign_key('attendance_lists_id_meal_type_fkey', 'attendance_lists', 'units', ['id_meal_type'], ['id_unit'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
