"""empty message

Revision ID: db410ca4c557
Revises: 
Create Date: 2024-03-20 16:05:14.471137

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'db410ca4c557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
                    sa.Column('id_school', sa.Integer(), nullable=False),
                    sa.Column('name_of_school', sa.String(), nullable=False),
                    sa.Column('post_code', sa.Integer(), nullable=False),
                    sa.Column('street_name', sa.String(), nullable=False),
                    sa.Column('street_number', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id_school')
                    )
    op.create_table('intendants',
                    sa.Column('id_intendant', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('id_school', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['id_school'], ['schools.id_school'], ),
                    sa.PrimaryKeyConstraint('id_intendant')
                    )
    op.create_index(op.f('ix_intendants_email'), 'intendants', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intendants_email'), table_name='intendants')
    op.drop_table('intendants')
    op.drop_table('schools')
    # ### end Alembic commands ###
